name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(node -p "require('./manifest.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extension version: $VERSION"

      - name: Rename zip file with version
        run: |
          cd dist
          mv link-timer.zip link-timer-v${{ steps.get_version.outputs.version }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/link-timer-v${{ steps.get_version.outputs.version }}.zip
          body: |
            ## Link Timer Chrome Extension v${{ steps.get_version.outputs.version }}

            ### 安装方法
            1. 下载 `link-timer-v${{ steps.get_version.outputs.version }}.zip`
            2. 解压文件
            3. 打开 Chrome 浏览器，访问 `chrome://extensions/`
            4. 开启"开发者模式"
            5. 点击"加载已解压的扩展程序"，选择解压后的文件夹

            ### 更新日志
            请查看提交记录了解详细变更
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}